/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness + DB reachability (D-A6 open question, settled: yes).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Events
         * @description ``GET /api/v1/events`` (task 2.2): every event, freshly scanned.
         *
         *     One unreadable event costs one error row, never the list (``list_events``
         *     isolates per event). What remains are the whole-list failures, reported
         *     distinctly in the shared problem shape: an unreachable job store as the 503
         *     ``/healthz`` returns, a walk of the project root that fails as the scan-failure
         *     502. Neither is retried and neither degrades into a partial list.
         */
        get: operations["get_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description ``GET /api/v1/events/{event_id}/analysis`` (task 2.4): cached segments only.
         *
         *     Registered *before* the ``{event_id:path}`` detail route below: both patterns
         *     are greedy over ``/``, and Starlette matches routes in registration order, so
         *     the more specific ``/analysis`` suffix must be tried first or the detail route
         *     would swallow it (``event_id`` ending in literal ``/analysis``).
         */
        get: operations["get_analysis_api_v1_events__event_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/reel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reel
         * @description ``GET /api/v1/events/{event_id}/reel``: the editorial document as authored.
         *
         *     The exact inverse of the PUT below — same model, same serializer — so a client
         *     may submit what it read without hand-building a write body. Registered *before*
         *     the greedy ``{event_id:path}`` detail route for the reason the ``/analysis``
         *     route documents. The response carries an ``ETag`` for the optional ``If-Match``
         *     precondition on the write; there is deliberately no conditional GET (D-R4).
         */
        get: operations["get_reel_api_v1_events__event_id__reel_get"];
        /**
         * Put Reel
         * @description ``PUT /api/v1/events/{event_id}/reel``: apply a desired editorial state (D-E2).
         *
         *     A coarse whole-document write: ``payload`` is the complete desired editorial
         *     state, merged onto the event's existing structure (never replacing the file
         *     outright, D-E1) and validated fail-loud before anything is persisted. The
         *     route carries no editorial logic of its own (D-E6) — it resolves the event,
         *     delegates to the engine operation, and echoes the persisted document plus the
         *     event's resulting staleness verdict (computed free, D-E5) so the client needs
         *     no follow-up GET. The write never enqueues and never touches the render
         *     manifest.
         *
         *     A successful write carries an ``ETag`` for the state it just persisted,
         *     computed from the returned document by the same helper ``get_reel`` uses, so a
         *     client may chain conditional writes with no intervening read. A ``412`` carries
         *     none: a client that lost the race must re-read before it overwrites.
         */
        put: operations["put_reel_api_v1_events__event_id__reel_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description ``GET /api/v1/events/{event_id}`` (task 2.3): current detail from disk.
         */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description ``GET /api/v1/jobs`` (task 3.2): optionally filtered by status, oldest first.
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description ``POST /api/v1/jobs`` (task 3.1, gated per change-detection §8.14).
         *
         *     Idempotent enqueue, 409 on active duplicate, 200 "fresh — not enqueued" when
         *     the event is fresh and ``force`` is false. The API never transitions job
         *     status itself (D-A6) — the gate decision is made here, at enqueue, the same
         *     as the CLI's own ``enqueue``.
         */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description ``GET /api/v1/jobs/{id}`` (task 3.2): one job's full detail.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description ``POST /api/v1/jobs/{id}/cancel`` (task 3.3): request_cancel, tri-state outcome.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisOut
         * @description An event's cached analysis (D-A3 open question: raw sidecar segments, per clip).
         *
         *     ``analyzed`` distinguishes "never analyzed" (``False``, ``segments`` empty)
         *     from "analyzed, found nothing" (``True``, ``segments`` empty) — the sidecar
         *     cache is per-clip, so this is true when at least one clip has a cache entry.
         */
        AnalysisOut: {
            /** Analyzed */
            analyzed: boolean;
            /**
             * Segments
             * @default {}
             */
            segments: {
                [key: string]: components["schemas"]["SegmentOut"][];
            };
        };
        /**
         * CancelResult
         * @description The body of ``POST /api/v1/jobs/{id}/cancel`` (D-S6 tri-state, task 3.3).
         */
        CancelResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /** Outcome */
            outcome: string;
        };
        /**
         * ChapterBody
         * @description One chapter in an editorial write: a name and its ordered clip identities.
         */
        ChapterBody: {
            /** Name */
            name: string;
            /**
             * Clips
             * @default []
             */
            clips: string[];
        };
        /**
         * ChapterOut
         * @description One chapter: its name (``""`` is the default/root chapter) and ordered clips.
         */
        ChapterOut: {
            /** Name */
            name: string;
            /**
             * Clips
             * @default []
             */
            clips: components["schemas"]["ClipOut"][];
        };
        /**
         * ClipOut
         * @description One clip: identity, reconcile status, and the file facts a reorder view needs.
         *
         *     ``size`` (bytes) and ``mtime`` (timezone-aware UTC) come from the clip's own
         *     directory entry — **file** facts, never media facts. Nothing here is decoded or
         *     probed, so the detail response stays probe-free (Principle IV); duration,
         *     dimensions and codec belong to the analysis cache, not this shape. Both are
         *     ``None`` for a clip the document references but disk does not have: absence is
         *     reported, never fabricated as a zero or an epoch (Principle I).
         */
        ClipOut: {
            /** Identity */
            identity: string;
            /** Status */
            status: string;
            /** Size */
            size?: number | null;
            /** Mtime */
            mtime?: string | null;
        };
        /**
         * ClipPropertiesBody
         * @description Per-clip editorial properties in the ``clips`` map (editorial-write, D-E2).
         */
        ClipPropertiesBody: {
            /**
             * Trims
             * @default []
             */
            trims: components["schemas"]["TrimBody"][];
            /** Title */
            title?: boolean | null;
            /** Rotate */
            rotate?: number | null;
            /**
             * Exclude
             * @default false
             */
            exclude: boolean;
        };
        /**
         * EditorialDocumentBody
         * @description The complete desired (request) or persisted (response) editorial state.
         *
         *     A coarse whole-document shape (D-E2): the client sends every editable
         *     section, and the server merges it onto the event's existing structure rather
         *     than replacing the file (D-E1). Unknown fields are rejected (fail-loud) rather
         *     than silently ignored.
         */
        "EditorialDocumentBody-Input": {
            /** @default {} */
            metadata: components["schemas"]["MetadataBody"];
            /**
             * Look
             * @default {}
             */
            look: {
                [key: string]: unknown;
            };
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterBody"][];
            /**
             * Clips
             * @default {}
             */
            clips: {
                [key: string]: components["schemas"]["ClipPropertiesBody"];
            };
            /**
             * Ignore
             * @default []
             */
            ignore: string[];
        };
        /**
         * EditorialDocumentBody
         * @description The complete desired (request) or persisted (response) editorial state.
         *
         *     A coarse whole-document shape (D-E2): the client sends every editable
         *     section, and the server merges it onto the event's existing structure rather
         *     than replacing the file (D-E1). Unknown fields are rejected (fail-loud) rather
         *     than silently ignored.
         */
        "EditorialDocumentBody-Output": {
            /** @default {} */
            metadata: components["schemas"]["MetadataBody"];
            /**
             * Look
             * @default {}
             */
            look: {
                [key: string]: unknown;
            };
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterBody"][];
            /**
             * Clips
             * @default {}
             */
            clips: {
                [key: string]: components["schemas"]["ClipPropertiesBody"];
            };
            /**
             * Ignore
             * @default []
             */
            ignore: string[];
        };
        /**
         * EditorialWriteResult
         * @description The response of ``PUT /api/v1/events/{event_id}/reel``: persisted state + verdict.
         *
         *     Echoing the persisted document lets the client observe server-side
         *     normalization and the event's new staleness verdict without a follow-up GET
         *     (open question, design.md, settled here).
         */
        EditorialWriteResult: {
            document: components["schemas"]["EditorialDocumentBody-Output"];
            staleness: components["schemas"]["StalenessOut"];
        };
        /**
         * EnqueueRequest
         * @description The body of ``POST /api/v1/jobs``.
         */
        EnqueueRequest: {
            /** Event Id */
            event_id: string;
            /**
             * Device
             * @default auto
             */
            device: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * EventDetailOut
         * @description One event's full detail: metadata, ordered chapters/clips, reconcile state,
         *     and its staleness verdict (change-detection, §8.14).
         */
        EventDetailOut: {
            /** Event Id */
            event_id: string;
            /** Title */
            title?: string | null;
            /** Date */
            date?: string | null;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterOut"][];
            /**
             * Missing
             * @default []
             */
            missing: string[];
            latest_job?: components["schemas"]["JobSummaryOut"] | null;
            staleness: components["schemas"]["StalenessOut"];
        };
        /**
         * EventErrorOut
         * @description An event the list could not read, in place of its summary (per-event isolation).
         *
         *     Carries no clip counts, staleness or title: those are exactly what could not be
         *     read, and absence is reported, never faked as zero (Principle I).
         */
        EventErrorOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "error";
            /** Event Id */
            event_id: string;
            failure: components["schemas"]["EventFailure"];
            /** Detail */
            detail: string;
        };
        /**
         * EventFailure
         * @description Why an event could not be listed: the API's classification of engine errors.
         * @enum {string}
         */
        EventFailure: "unparseable_reel_yaml" | "unusable_metadata" | "unreadable_disk";
        /**
         * EventSummaryOut
         * @description One event as listed by ``GET /api/v1/events``.
         */
        EventSummaryOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "event";
            /** Event Id */
            event_id: string;
            /** Title */
            title?: string | null;
            /** Date */
            date?: string | null;
            /** Location */
            location?: string | null;
            /** Clip Count */
            clip_count: number;
            /** New Count */
            new_count: number;
            /** Missing Count */
            missing_count: number;
            latest_job?: components["schemas"]["JobSummaryOut"] | null;
            staleness: components["schemas"]["StalenessOut"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobOut
         * @description One job's full detail, mirroring ``jobs show`` (task 3.2).
         */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /** Event Dir */
            event_dir: string;
            /** Project Root */
            project_root?: string | null;
            /** Device */
            device: string;
            /** Progress */
            progress: number;
            /** Worker Id */
            worker_id?: string | null;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Requeue Count */
            requeue_count: number;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Fingerprint */
            fingerprint?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * JobStatus
         * @description The five lifecycle states a job may occupy (D-P4).
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "done" | "failed" | "canceled";
        /**
         * JobSummaryOut
         * @description The latest job for an event, as embedded in the events list (D-A3).
         *
         *     ``status`` is typed with the job store's own closed vocabulary, so the schema
         *     publishes the enumeration and generated clients get an exhaustive union
         *     (D-8, §4.10). ``JobStatus`` is a ``str`` enum: the wire values are unchanged.
         */
        JobSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MetadataBody
         * @description Event metadata in an editorial write.
         */
        MetadataBody: {
            /** Title */
            title?: string | null;
            /** Date */
            date?: string | null;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ProblemOut
         * @description The shared problem body every deliberate error uses (D-A6), as published in the schema.
         *
         *     Schema-only: routes still return ``problem.problem_response``'s ``JSONResponse``,
         *     which FastAPI does not validate against this model. ``extra="allow"`` keeps
         *     route-specific fields (e.g. a 409's existing job ``id``) legal without this
         *     model enumerating them; the named optional fields are the ones clients branch on.
         */
        ProblemOut: {
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Check */
            check?: string | null;
            /** Event Id */
            event_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SegmentOut
         * @description One detected segment (black/white/freeze span) for a clip.
         */
        SegmentOut: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * StalenessOut
         * @description An event's staleness verdict: fresh, or stale with the changed components.
         *
         *     ``reasons`` is typed with the gate's own closed vocabulary rather than
         *     ``List[str]``, so the OpenAPI schema publishes the enumeration and the
         *     generated client types get an exhaustive union: renaming a reason in the
         *     engine becomes a client build error instead of a silent runtime change
         *     (D-8, §4.10). The wire values are the gate's strings, unchanged.
         */
        StalenessOut: {
            /** Stale */
            stale: boolean;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["StalenessReason"][];
        };
        /**
         * StalenessReason
         * @description The closed set of reasons a stale verdict may cite.
         *
         *     A :class:`~enum.StrEnum` member *is* a ``str``, so a reason compares, joins,
         *     formats and serializes exactly as the bare string it replaces — the wire
         *     values are unchanged by construction. The component members mirror
         *     :data:`~auto_reel_ng.staleness.fingerprint.COMPONENTS`, in that order (asserted
         *     by the gate's tests, so a new component cannot ship without its reason).
         * @enum {string}
         */
        StalenessReason: "no_manifest" | "output" | "editorial" | "defaults" | "clip_set" | "engine";
        /**
         * TrimBody
         * @description One cut span (``in``/``out``/``reason``), the reel.yaml YAML vocabulary.
         *
         *     ``in`` is a Python keyword, so the field is renamed and aliased for the wire.
         */
        TrimBody: {
            /** In */
            in: number;
            /** Out */
            out: number;
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EventSummaryOut"] | components["schemas"]["EventErrorOut"])[];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_analysis_api_v1_events__event_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reel_api_v1_events__event_id__reel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorialDocumentBody-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_reel_api_v1_events__event_id__reel_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditorialDocumentBody-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorialWriteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnqueueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
