/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness + DB reachability (D-A6 open question, settled: yes).
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Clip Media
         * @description ``GET`` and ``HEAD /api/v1/events/{event_id}/media?clip=``: one clip's file, unchanged.
         *
         *     ``HEAD`` is the ``GET`` without its body: the same lookup, open and status, the same
         *     headers (``FileResponse`` drops the body). ``If-None-Match`` and ``If-Modified-Since``
         *     answer 304 for both.
         *
         *     The clip must be one discovery lists on disk for an event the events list shows,
         *     matched exactly: the thumbnail's lookup. 404 for an unknown event, an unlisted
         *     identity, or a file gone by the time it is opened; 502 with the list's ``failure``
         *     when the event cannot be listed, and with no kind for an unknown layout or a file
         *     that cannot be read. Sync on purpose: the lookup is a listing, a stat and an open,
         *     run in the threadpool; ``FileResponse`` then streams on the event loop.
         */
        get: operations["get_clip_media_api_v1_events__event_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get Clip Media
         * @description ``GET`` and ``HEAD /api/v1/events/{event_id}/media?clip=``: one clip's file, unchanged.
         *
         *     ``HEAD`` is the ``GET`` without its body: the same lookup, open and status, the same
         *     headers (``FileResponse`` drops the body). ``If-None-Match`` and ``If-Modified-Since``
         *     answer 304 for both.
         *
         *     The clip must be one discovery lists on disk for an event the events list shows,
         *     matched exactly: the thumbnail's lookup. 404 for an unknown event, an unlisted
         *     identity, or a file gone by the time it is opened; 502 with the list's ``failure``
         *     when the event cannot be listed, and with no kind for an unknown layout or a file
         *     that cannot be read. Sync on purpose: the lookup is a listing, a stat and an open,
         *     run in the threadpool; ``FileResponse`` then streams on the event loop.
         */
        head: operations["get_clip_media_api_v1_events__event_id__media_head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/movie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Movie
         * @description ``GET`` and ``HEAD /api/v1/events/{event_id}/movie``: the event's rendered movie, streamed.
         *
         *     ``HEAD`` and the conditional headers behave as for the clip route.
         *
         *     The movie is the file the staleness gate counts (``staleness.rendered_output``):
         *     it exists exactly when the event's staleness cites neither ``no_manifest`` nor
         *     ``output``. 404 for an unknown event, no render record, a recorded movie that is
         *     gone, a name outside the output directory, or something other than a file; 502
         *     with the ``failure`` the event detail gives when the event cannot be read, and with
         *     no kind for an unknown layout or a movie that cannot be read.
         */
        get: operations["get_movie_api_v1_events__event_id__movie_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Get Movie
         * @description ``GET`` and ``HEAD /api/v1/events/{event_id}/movie``: the event's rendered movie, streamed.
         *
         *     ``HEAD`` and the conditional headers behave as for the clip route.
         *
         *     The movie is the file the staleness gate counts (``staleness.rendered_output``):
         *     it exists exactly when the event's staleness cites neither ``no_manifest`` nor
         *     ``output``. 404 for an unknown event, no render record, a recorded movie that is
         *     gone, a name outside the output directory, or something other than a file; 502
         *     with the ``failure`` the event detail gives when the event cannot be read, and with
         *     no kind for an unknown layout or a movie that cannot be read.
         */
        head: operations["get_movie_api_v1_events__event_id__movie_head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Events
         * @description ``GET /api/v1/events`` (task 2.2): every event, freshly scanned.
         *
         *     One unreadable event costs one error row, never the list (``list_events``
         *     isolates per event). What remains are the whole-list failures, reported
         *     distinctly in the shared problem shape: an unreachable job store as the 503
         *     ``/healthz`` returns, a walk of the project root that fails as the scan-failure
         *     502. Neither is retried and neither degrades into a partial list.
         */
        get: operations["get_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description ``GET /api/v1/events/{event_id}/analysis`` (task 2.4): cached segments only.
         *
         *     Answers only for an id the events list shows, like the thumbnail and media
         *     routes: 404 for any other directory (a year folder, an event's ``original/``, a
         *     ``.reelignore``d event). 502 for an event folder that cannot be listed (with the
         *     list's ``failure`` kind) and for a layout the service cannot resolve (with no
         *     kind). The database is never touched.
         *
         *     Registered *before* the ``{event_id:path}`` detail route below: both patterns
         *     are greedy over ``/``, and Starlette matches routes in registration order, so
         *     the more specific ``/analysis`` suffix must be tried first or the detail route
         *     would swallow it (``event_id`` ending in literal ``/analysis``).
         */
        get: operations["get_analysis_api_v1_events__event_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/reel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reel
         * @description ``GET /api/v1/events/{event_id}/reel``: the editorial document as authored.
         *
         *     The exact inverse of the PUT below — same model, same serializer — so a client
         *     may submit what it read without hand-building a write body. Registered *before*
         *     the greedy ``{event_id:path}`` detail route for the reason the ``/analysis``
         *     route documents. The response carries an ``ETag`` for the optional ``If-Match``
         *     precondition on the write; there is deliberately no conditional GET (D-R4).
         */
        get: operations["get_reel_api_v1_events__event_id__reel_get"];
        /**
         * Put Reel
         * @description ``PUT /api/v1/events/{event_id}/reel``: apply a desired editorial state (D-E2).
         *
         *     A coarse whole-document write: ``payload`` is the complete desired editorial
         *     state, merged onto the event's existing structure (never replacing the file
         *     outright, D-E1) and validated fail-loud before anything is persisted. The
         *     route carries no editorial logic of its own (D-E6) — it resolves the event,
         *     delegates to the engine operation, and echoes the persisted document plus the
         *     event's resulting staleness verdict (computed free, D-E5) so the client needs
         *     no follow-up GET. The write never enqueues and never touches the render
         *     manifest.
         *
         *     A successful write carries an ``ETag`` for the state it just persisted,
         *     computed from the returned document by the same helper ``get_reel`` uses, so a
         *     client may chain conditional writes with no intervening read. A ``412`` carries
         *     none: a client that lost the race must re-read before it overwrites.
         *
         *     ``If-Match`` is published as a parameter, but read from every header line the
         *     request carries (RFC 9110: repeated lines are one comma-separated list): the
         *     parameter would hold only the first. A request that carries the header at all,
         *     even empty, is conditional.
         *
         *     Failures answer by cause and write nothing: 400 for an invalid submitted state
         *     (with ``failure: unusable_metadata`` when the engine refuses a state that
         *     leaves the event without a real date or title), 404, 412, and 502 for the disk:
         *     an existing document that cannot be read (with its ``failure`` kind, as the
         *     reads report it) or a save the filesystem refuses (naming the OS error).
         */
        put: operations["put_reel_api_v1_events__event_id__reel_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thumbnail
         * @description ``GET /api/v1/events/{event_id}/thumbnail?clip=``: one clip's thumbnail (D-11).
         *
         *     Registered *before* the greedy ``{event_id:path}`` detail route for the reason
         *     the ``/analysis`` route documents; the clip identity is a query parameter
         *     because two greedy path parameters cannot be told apart.
         *
         *     ``async`` on purpose: a request waiting for an extraction slot waits on the
         *     gate's ``asyncio`` primitives and holds no threadpool worker, so a page of cold
         *     thumbnails cannot starve the other routes. Every blocking step (the listing,
         *     the stat, reading the JPEG, the extraction) runs in the threadpool.
         *
         *     Failures answer by cause and carry no caching headers: 404 for an id the events
         *     list does not show as an event, or a clip that is not on disk in it; 502 with
         *     ``thumbnail_failure`` when the engine cannot make this clip's thumbnail, with the
         *     list's ``failure`` when the event cannot be listed, and with neither for the cache
         *     or ``config.yaml``. Nothing is written into the library, and the database is
         *     never touched.
         *
         *     ``If-None-Match`` is published as a parameter, but read from every header line
         *     the request carries: the parameter would hold only the first.
         */
        get: operations["get_thumbnail_api_v1_events__event_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description ``GET /api/v1/events/{event_id}`` (task 2.3): current detail from disk.
         *
         *     An event the list would show as an error row is the scan-failure 502 here,
         *     carrying the same ``failure`` kind and ``detail`` as that row, never a 500.
         */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description ``GET /api/v1/jobs`` (task 3.2): the served project's jobs, by status, oldest first.
         */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description ``POST /api/v1/jobs`` (task 3.1, gated per change-detection §8.14).
         *
         *     Idempotent enqueue, 409 on active duplicate or a missing played clip, 200 "fresh —
         *     not enqueued" when the event is fresh and ``force`` is false. The API never
         *     transitions job status itself (D-A6) — the gate decision is made here, at enqueue,
         *     the same as the CLI's own ``enqueue``.
         *
         *     The id must be one the events list shows, spelled as it spells it (else the 404 of an
         *     unknown event), and the event must be processable (else the events reads' 502 with its
         *     failure kind). The output-collision check comes next, as the CLI decides it before
         *     anything else: an event whose output path another event of the project claims is a 409
         *     ``output_collision``, fresh or stale, forced or not — never gated, never "already
         *     active". A walk that fails leaves the rule unchecked, so it is the events list's
         *     scan-failure 502 and nothing is enqueued (Principle I). An active job is answered next,
         *     and then an event that plays a clip missing from disk is a 409 ``missing_clips`` naming
         *     the clips — fresh or stale, forced or not, since that render could only fail at probe.
         */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description ``GET /api/v1/jobs/{id}`` (task 3.2): one of the served project's jobs, in full.
         */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description ``POST /api/v1/jobs/{id}/cancel`` (task 3.3): the store's cancel and its outcome.
         *
         *     The one read before the store call decides only *whether* this service may
         *     cancel the job — the served project's own — and a job's project root is never
         *     written after insert, so that read cannot go stale. The outcome and the echoed
         *     status still come from the locked transaction that applied the cancel, never
         *     from that read, so a worker's claim landing in between can never make them
         *     disagree.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisOut
         * @description An event's cached analysis (D-A3 open question: raw sidecar segments, per clip).
         *
         *     ``analyzed`` distinguishes "never analyzed" (``False``, ``segments`` empty)
         *     from "analyzed, found nothing" (``True``, ``segments`` empty) — the sidecar
         *     cache is per-clip, so this is true when at least one clip has a cache entry.
         */
        AnalysisOut: {
            /** Analyzed */
            analyzed: boolean;
            /**
             * Segments
             * @default {}
             */
            segments: {
                [key: string]: components["schemas"]["SegmentOut"][];
            };
        };
        /**
         * CancelOutcome
         * @description What a cancel request did to a job (D-S6): the outcome the store applied.
         * @enum {string}
         */
        CancelOutcome: "flagged-running" | "canceled-queued" | "no-op-terminal";
        /**
         * CancelResult
         * @description The body of ``POST /api/v1/jobs/{id}/cancel``: the outcome the store applied (D-S6).
         *
         *     ``outcome`` and ``status`` come from the one transaction that applied the cancel,
         *     so they always agree. ``outcome`` is typed with the store's own closed vocabulary,
         *     so the schema publishes the enumeration and generated clients get an exhaustive
         *     union (D-8, §4.10); the wire values are unchanged.
         */
        CancelResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            outcome: components["schemas"]["CancelOutcome"];
        };
        /**
         * ChapterBody
         * @description One chapter in an editorial write: a name and its ordered clip identities.
         */
        ChapterBody: {
            /** Name */
            name: string;
            /**
             * Clips
             * @default []
             */
            clips: string[];
        };
        /**
         * ChapterOut
         * @description One chapter: its name (``""`` is the default/root chapter) and ordered clips.
         */
        ChapterOut: {
            /** Name */
            name: string;
            /**
             * Clips
             * @default []
             */
            clips: components["schemas"]["ClipOut"][];
        };
        /**
         * ClipOut
         * @description One clip: identity, reconcile status, and the file facts a reorder view needs.
         *
         *     ``size`` (bytes) and ``mtime`` (timezone-aware UTC) come from the clip's own
         *     directory entry — **file** facts, never media facts. Nothing here is decoded or
         *     probed, so the detail response stays probe-free (Principle IV); dimensions and codec
         *     belong to the analysis cache, not this shape. Both are ``None`` for a clip the
         *     document references but disk does not have: absence is reported, never fabricated as
         *     a zero or an epoch (Principle I).
         *
         *     ``duration`` (seconds) is the one media fact, and it is **not probed here**: it is the
         *     number the thumbnail operation measured for this exact file (name, size, mtime), read
         *     from the thumbnail cache's sidecar. ``None`` means unknown — a missing clip, a
         *     thumbnail not yet made for the file as it is now, an unusable sidecar or
         *     ``thumbnails`` configuration — never zero or a guess. It is the probe's number, so a
         *     browser may read a few tens of milliseconds more from the same file.
         *
         *     ``status`` is typed with reconcile's own closed vocabulary, so the schema
         *     publishes the enumeration and generated clients get an exhaustive union
         *     (D-8, §4.10). ``ClipStatus`` is a ``StrEnum``: the wire values are unchanged.
         *
         *     ``excluded`` is a flag **beside** ``status``, not a member of it: it is true when the
         *     document's ``clips`` map marks the identity ``exclude: true``, so a render drops the
         *     clip from the movie without probing it. An excluded clip reports its own status (an
         *     excluded clip whose file is gone is ``missing`` and ``excluded``). It is false for a
         *     NEW or IGNORED clip (the document holds no properties for a clip no chapter lists)
         *     and for every clip of an event without a ``reel.yaml``.
         */
        ClipOut: {
            /** Identity */
            identity: string;
            status: components["schemas"]["ClipStatus"];
            /** Size */
            size?: number | null;
            /** Mtime */
            mtime?: string | null;
            /** Duration */
            duration?: number | null;
            /**
             * Excluded
             * @default false
             */
            excluded: boolean;
        };
        /**
         * ClipPropertiesBody
         * @description Per-clip editorial properties in the ``clips`` map (editorial-write, D-E2).
         */
        ClipPropertiesBody: {
            /**
             * Trims
             * @default []
             */
            trims: components["schemas"]["TrimBody"][];
            /** Title */
            title?: boolean | null;
            /** Rotate */
            rotate?: number | null;
            /**
             * Exclude
             * @default false
             */
            exclude: boolean;
        };
        /**
         * ClipStatus
         * @description How a clip relates the disk to the document.
         *
         *     A :class:`~enum.StrEnum`, like the other engine vocabularies: a member *is* its
         *     string value, so the API publishes this set as-is and the wire value is the
         *     same ``new``/``missing``/``active``/``ignored`` string.
         * @enum {string}
         */
        ClipStatus: "new" | "missing" | "active" | "ignored";
        /**
         * EditorialDocumentBody
         * @description The complete desired (request) or persisted (response) editorial state.
         *
         *     A coarse whole-document shape (D-E2): the client sends every editable
         *     section, and the server merges it onto the event's existing structure rather
         *     than replacing the file (D-E1). Unknown fields are rejected (fail-loud) rather
         *     than silently ignored.
         */
        "EditorialDocumentBody-Input": {
            /** @default {} */
            metadata: components["schemas"]["MetadataBody"];
            /**
             * Look
             * @default {}
             */
            look: {
                [key: string]: unknown;
            };
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterBody"][];
            /**
             * Clips
             * @default {}
             */
            clips: {
                [key: string]: components["schemas"]["ClipPropertiesBody"];
            };
            /**
             * Ignore
             * @default []
             */
            ignore: string[];
        };
        /**
         * EditorialDocumentBody
         * @description The complete desired (request) or persisted (response) editorial state.
         *
         *     A coarse whole-document shape (D-E2): the client sends every editable
         *     section, and the server merges it onto the event's existing structure rather
         *     than replacing the file (D-E1). Unknown fields are rejected (fail-loud) rather
         *     than silently ignored.
         */
        "EditorialDocumentBody-Output": {
            /** @default {} */
            metadata: components["schemas"]["MetadataBody"];
            /**
             * Look
             * @default {}
             */
            look: {
                [key: string]: unknown;
            };
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterBody"][];
            /**
             * Clips
             * @default {}
             */
            clips: {
                [key: string]: components["schemas"]["ClipPropertiesBody"];
            };
            /**
             * Ignore
             * @default []
             */
            ignore: string[];
        };
        /**
         * EditorialWriteResult
         * @description The response of ``PUT /api/v1/events/{event_id}/reel``: persisted state + verdict.
         *
         *     Echoing the persisted document lets the client observe server-side
         *     normalization and the event's new staleness verdict without a follow-up GET
         *     (open question, design.md, settled here).
         */
        EditorialWriteResult: {
            document: components["schemas"]["EditorialDocumentBody-Output"];
            staleness: components["schemas"]["StalenessOut"];
        };
        /**
         * EnqueueConflict
         * @description Why ``POST /api/v1/jobs`` refused an event with a 409: the API's classification.
         * @enum {string}
         */
        EnqueueConflict: "active_job" | "output_collision" | "missing_clips";
        /**
         * EnqueueRequest
         * @description The body of ``POST /api/v1/jobs``.
         */
        EnqueueRequest: {
            /** Event Id */
            event_id: string;
            /**
             * Device
             * @default auto
             */
            device: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * EventDetailOut
         * @description One event's full detail: metadata, ordered chapters/clips, reconcile state,
         *     and its staleness verdict (change-detection, §8.14).
         *
         *     ``missing`` lists every clip the document lists that disk does not have, excluded or
         *     not. ``blocking_missing`` is the subset a render needs: the missing clips the document
         *     does not exclude (an excluded clip is never probed, so its absence cannot fail a
         *     render).
         */
        EventDetailOut: {
            /** Event Id */
            event_id: string;
            /** Title */
            title?: string | null;
            /** Date */
            date?: string | null;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["ChapterOut"][];
            /**
             * Missing
             * @default []
             */
            missing: string[];
            /**
             * Blocking Missing
             * @default []
             */
            blocking_missing: string[];
            latest_job?: components["schemas"]["JobSummaryOut"] | null;
            staleness: components["schemas"]["StalenessOut"];
        };
        /**
         * EventErrorOut
         * @description An event the list could not read, in place of its summary (per-event isolation).
         *
         *     Carries no clip counts, staleness or title: those are exactly what could not be
         *     read, and absence is reported, never faked as zero (Principle I).
         */
        EventErrorOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "error";
            /** Event Id */
            event_id: string;
            failure: components["schemas"]["EventFailure"];
            /** Detail */
            detail: string;
        };
        /**
         * EventFailure
         * @description Why an event could not be listed: the API's classification of engine errors.
         * @enum {string}
         */
        EventFailure: "unparseable_reel_yaml" | "unusable_metadata" | "unreadable_disk";
        /**
         * EventSummaryOut
         * @description One event as listed by ``GET /api/v1/events``.
         *
         *     ``clip_count`` is the clips the event lists that are not ignored (ACTIVE, NEW and
         *     MISSING), the number the event's detail page counts; ``ignored_count`` is the IGNORED
         *     ones, which ``clip_count`` leaves out. ``missing_count`` counts every missing clip;
         *     ``blocking_missing_count`` only those a render needs (the detail's ``blocking_missing``).
         */
        EventSummaryOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "event";
            /** Event Id */
            event_id: string;
            /** Title */
            title?: string | null;
            /** Date */
            date?: string | null;
            /** Location */
            location?: string | null;
            /** Clip Count */
            clip_count: number;
            /** Ignored Count */
            ignored_count: number;
            /** New Count */
            new_count: number;
            /** Missing Count */
            missing_count: number;
            /** Blocking Missing Count */
            blocking_missing_count: number;
            latest_job?: components["schemas"]["JobSummaryOut"] | null;
            staleness: components["schemas"]["StalenessOut"];
        };
        /**
         * FreshResult
         * @description The body of ``POST /api/v1/jobs`` when the event is fresh and not enqueued (D-C3).
         */
        FreshResult: {
            /** Event Id */
            event_id: string;
            /**
             * Status
             * @constant
             */
            status: "fresh";
            /** Fingerprint */
            fingerprint: string;
            /** Manifest */
            manifest: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobOut
         * @description One job's full detail, mirroring ``jobs show`` (task 3.2).
         */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Event Dir
             * @description The event's id: the root-relative event directory, the same value the events routes take as {event_id} and return as event_id
             */
            event_dir: string;
            /** Project Root */
            project_root?: string | null;
            /** Device */
            device: string;
            /** Progress */
            progress: number;
            /** Worker Id */
            worker_id?: string | null;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Requeue Count */
            requeue_count: number;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Fingerprint */
            fingerprint?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * JobStatus
         * @description The five lifecycle states a job may occupy (D-P4).
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "done" | "failed" | "canceled";
        /**
         * JobSummaryOut
         * @description The latest job for an event, as embedded in the events list and detail (D-A3).
         *
         *     A projection of the job's detail (``JobOut``): every field here has the same value,
         *     meaning and schema definition there. ``started_at``/``finished_at`` are null until the
         *     store stamps them (a claim; a terminal transition), never substituted.
         *
         *     ``cancel_requested`` and ``requeue_count`` are required (never null in the store) so a
         *     reader can tell a cancel pending and a job that went back to the queue after a claim
         *     from a read alone; a requeue leaves ``cancel_requested`` as it was.
         *
         *     ``status`` is typed with the job store's own closed vocabulary, so the schema
         *     publishes the enumeration and generated clients get an exhaustive union
         *     (D-8, §4.10). ``JobStatus`` is a ``str`` enum: the wire values are unchanged.
         */
        JobSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Requeue Count */
            requeue_count: number;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * MetadataBody
         * @description Event metadata in an editorial write.
         */
        MetadataBody: {
            /** Title */
            title?: string | null;
            /** Date */
            date?: string | null;
            /** Location */
            location?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ProblemOut
         * @description The shared problem body every deliberate error uses (D-A6), as published in the schema.
         *
         *     Schema-only: routes still return ``problem.problem_response``'s ``JSONResponse``,
         *     which FastAPI does not validate against this model. ``extra="allow"`` keeps an
         *     undeclared route-specific field legal; a field clients branch on is declared
         *     below as a named optional field, so the generated types carry it without a cast.
         */
        ProblemOut: {
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Check */
            check?: string | null;
            /** Event Id */
            event_id?: string | null;
            failure?: components["schemas"]["EventFailure"] | null;
            /** Job Id */
            job_id?: string | null;
            conflict?: components["schemas"]["EnqueueConflict"] | null;
            /** Claimed By */
            claimed_by?: string[] | null;
            /** Missing */
            missing?: string[] | null;
            thumbnail_failure?: components["schemas"]["ThumbnailFailure"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SegmentOut
         * @description One detected segment (black/white/freeze span) for a clip.
         */
        SegmentOut: {
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * StalenessOut
         * @description An event's staleness verdict: fresh, or stale with the changed components.
         *
         *     ``reasons`` is typed with the gate's own closed vocabulary rather than
         *     ``List[str]``, so the OpenAPI schema publishes the enumeration and the
         *     generated client types get an exhaustive union: renaming a reason in the
         *     engine becomes a client build error instead of a silent runtime change
         *     (D-8, §4.10). The wire values are the gate's strings, unchanged.
         *
         *     ``renamed_from`` and ``output_name`` are the gate's own: the bare names of the movie
         *     the last render wrote (still on disk) and of the one the next render writes. Both are
         *     set exactly when ``output_renamed`` is among ``reasons`` and null otherwise; they are
         *     always present on the wire.
         */
        StalenessOut: {
            /** Stale */
            stale: boolean;
            /**
             * Reasons
             * @default []
             */
            reasons: components["schemas"]["StalenessReason"][];
            /** Renamed From */
            renamed_from?: string | null;
            /** Output Name */
            output_name?: string | null;
        };
        /**
         * StalenessReason
         * @description The closed set of reasons a stale verdict may cite.
         *
         *     - ``no_manifest``: no readable record of a last render exists to compare against.
         *     - ``output``: the event's movie is missing from its expected path, and the last
         *       render's movie was not found under its old name either.
         *     - ``output_renamed``: the event's movie name (its title, date or location) changed
         *       since the last render, and a movie is still on disk under the old name. The next
         *       render writes the movie under the new name and leaves the old file where it is;
         *       a render of another event that now has the old name is refused unless forced
         *       (``render.claims.claimed_movie``), because this manifest still records that file. The
         *       verdict then also carries ``renamed_from`` and ``output_name``, the two file names.
         *     - ``editorial``, ``defaults``, ``clip_set``, ``engine``: that fingerprint component
         *       changed since the last render (the ``reel.yaml`` document, the project's look
         *       defaults, the clips on disk, the render engine).
         *
         *     A :class:`~enum.StrEnum` member *is* a ``str``, so a reason compares, joins,
         *     formats and serializes exactly as the bare string it replaces — the wire
         *     values are unchanged by construction. The component members mirror
         *     :data:`~auto_reel_ng.staleness.fingerprint.COMPONENTS`, in that order (asserted
         *     by the gate's tests, so a new component cannot ship without its reason).
         * @enum {string}
         */
        StalenessReason: "no_manifest" | "output" | "output_renamed" | "editorial" | "defaults" | "clip_set" | "engine";
        /**
         * ThumbnailFailure
         * @description Why a clip's thumbnail could not be served: the API's classification of engine errors.
         *
         *     A kind describes the *clip*, never the service: a thumbnail cache that cannot be
         *     written or an invalid ``config.yaml`` answers 502 with no kind at all.
         * @enum {string}
         */
        ThumbnailFailure: "thumbnail_failed";
        /**
         * TrimBody
         * @description One cut span (``in``/``out``/``reason``), the reel.yaml YAML vocabulary.
         *
         *     ``in`` is a Python keyword, so the field is renamed and aliased for the wire.
         */
        TrimBody: {
            /** In */
            in: number;
            /** Out */
            out: number;
            /** Reason */
            reason?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WsMessage
         * @description One frame on ``WS /api/v1/ws/jobs`` (D-A4): a snapshot, a delta batch or a heartbeat.
         *
         *     A WebSocket route is not an HTTP operation, so no path in the schema references
         *     this model: the application publishes it into the schema's components itself,
         *     so a client generated from the schema gets the frame's type without declaring it
         *     by hand (D-8, §4.10).
         */
        WsMessage: {
            type: components["schemas"]["WsMessageType"];
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
        };
        /**
         * WsMessageType
         * @description The closed set of frame types on ``WS /api/v1/ws/jobs`` (D-A4).
         * @enum {string}
         */
        WsMessageType: "snapshot" | "delta" | "heartbeat";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_clip_media_api_v1_events__event_id__media_get: {
        parameters: {
            query: {
                /** @description The clip's identity as the event detail lists it: its event-relative path */
                clip: string;
                /** @description An opaque version a client may send to give a changed file a new URL; ignored */
                v?: string | null;
            };
            header?: {
                "If-None-Match"?: string | null;
                "If-Modified-Since"?: string | null;
                Range?: string | null;
                "If-Range"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file */
            200: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description One byte range of the file */
            206: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    /** @description `bytes <first>-<last>/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description Not modified: `If-None-Match` names the current file, or, without it, `If-Modified-Since` is not before its modification time */
            304: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A malformed `Range` header (plain text) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description The range starts at or past the end of the file (plain text) */
            416: {
                headers: {
                    /** @description `bytes *\/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_clip_media_api_v1_events__event_id__media_head: {
        parameters: {
            query: {
                /** @description The clip's identity as the event detail lists it: its event-relative path */
                clip: string;
                /** @description An opaque version a client may send to give a changed file a new URL; ignored */
                v?: string | null;
            };
            header?: {
                "If-None-Match"?: string | null;
                "If-Modified-Since"?: string | null;
                Range?: string | null;
                "If-Range"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file */
            200: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description One byte range of the file */
            206: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    /** @description `bytes <first>-<last>/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description Not modified: `If-None-Match` names the current file, or, without it, `If-Modified-Since` is not before its modification time */
            304: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A malformed `Range` header (plain text) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description The range starts at or past the end of the file (plain text) */
            416: {
                headers: {
                    /** @description `bytes *\/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_movie_api_v1_events__event_id__movie_get: {
        parameters: {
            query?: {
                /** @description An opaque version a client may send to give a changed file a new URL; ignored */
                v?: string | null;
            };
            header?: {
                "If-None-Match"?: string | null;
                "If-Modified-Since"?: string | null;
                Range?: string | null;
                "If-Range"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file */
            200: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description One byte range of the file */
            206: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    /** @description `bytes <first>-<last>/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description Not modified: `If-None-Match` names the current file, or, without it, `If-Modified-Since` is not before its modification time */
            304: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A malformed `Range` header (plain text) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description The range starts at or past the end of the file (plain text) */
            416: {
                headers: {
                    /** @description `bytes *\/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_movie_api_v1_events__event_id__movie_head: {
        parameters: {
            query?: {
                /** @description An opaque version a client may send to give a changed file a new URL; ignored */
                v?: string | null;
            };
            header?: {
                "If-None-Match"?: string | null;
                "If-Modified-Since"?: string | null;
                Range?: string | null;
                "If-Range"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole file */
            200: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description One byte range of the file */
            206: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description The file's modification time */
                    "Last-Modified"?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    /** @description Always `bytes` */
                    "Accept-Ranges"?: string;
                    /** @description `inline`, with the file's own name */
                    "Content-Disposition"?: string;
                    /** @description `bytes <first>-<last>/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "video/*": string;
                };
            };
            /** @description Not modified: `If-None-Match` names the current file, or, without it, `If-Modified-Since` is not before its modification time */
            304: {
                headers: {
                    /** @description Strong entity-tag of the file: its size and mtime, in hex */
                    ETag?: string;
                    /** @description Always `private, no-cache` */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A malformed `Range` header (plain text) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description The range starts at or past the end of the file (plain text) */
            416: {
                headers: {
                    /** @description `bytes *\/<size>` */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EventSummaryOut"] | components["schemas"]["EventErrorOut"])[];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_analysis_api_v1_events__event_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_reel_api_v1_events__event_id__reel_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Strong entity-tag of the editorial state, for If-Match on the write */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorialDocumentBody-Output"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    put_reel_api_v1_events__event_id__reel_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditorialDocumentBody-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Strong entity-tag of the editorial state, for If-Match on the write */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorialWriteResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_thumbnail_api_v1_events__event_id__thumbnail_get: {
        parameters: {
            query: {
                /** @description The clip's identity as the event detail lists it: its event-relative path */
                clip: string;
                /** @description An opaque cache-busting version; accepted and ignored */
                v?: string | null;
            };
            header?: {
                "If-None-Match"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The clip's thumbnail: a JPEG fitted within 320x180 */
            200: {
                headers: {
                    /** @description Strong entity-tag of the thumbnail: the engine's cache key, quoted */
                    ETag?: string;
                    /** @description Always `private, max-age=86400` */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            /** @description Not modified: `If-None-Match` names the current thumbnail */
            304: {
                headers: {
                    /** @description Strong entity-tag of the thumbnail: the engine's cache key, quoted */
                    ETag?: string;
                    /** @description Always `private, max-age=86400` */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnqueueRequest"];
            };
        };
        responses: {
            /** @description The event is fresh; nothing was enqueued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreshResult"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemOut"];
                };
            };
        };
    };
}
